### PR TITLE
Remove flash8. (fixes #7)

### LINKED ISSUE #7: Munit example app hangs on RUN after swf8 target when running multiple targets
This issue only occurs for swf8 test  runner when run alongside other targets.

THE Command line hangs prior to results being captured.

Running the swf8 target only (using the -swf arg) works as expected.

Removing the swf8 test  from the bin directory prior to running runs all other targets correctly.

### PR DESCRIPTION
**Pull request by SlavaRa**
- Dropped support for Haxe 2
- Dropped support for flash8
- Dropped support for flash9

### CODE REVIEW

**Comment by SlavaRa** [comment]
@elsassph please check this and merge if all ok. After that I'll add a cs target, then nodejs, then python, then php7, then hl.
I did all this more than six months ago :)

**Comment by elsassph** [comment]
Why did you remove `haxelib.json`?

**Comment by SlavaRa** [comment]
Oh, sorry, fixed

**Comment by SlavaRa** [comment]
@elsassph now all ok?

**Comment by SlavaRa** [comment]
bump

**Comment by SlavaRa** [comment]
;(

**Comment by SlavaRa** [comment]
bump

**Comment by SlavaRa** [comment]
@elsassph Thanks

**Pull request merged**
