### PR TITLE
Added `-java` target

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@dpeek @mikestead @misprintt @Xwellz guys, please review and merge this PR. I'm also going to implement CSharp target.

**Comment by SlavaRa** [comment]
@elsassph if I reopen this PR it will be merged?

**Comment by elsassph** [comment]
Yes we can

**Comment by elsassph** [comment]
Amazing, thanks.

**Pull request merged**
