### PR TITLE
Fix for AS2 deprecation regression

### LINKED ISSUE #151: HTTPClient broken for Flash in 2.2.1
Flash support seems to be broken in 2.2.1. When creating a fresh project with `haxelib run munit config` (confirming everything with enter) and running `haxe test.hxml`, I get the following error:

>C:\HaxeToolkit\haxe\lib\munit/2,2,1/massive/munit/client/HTTPClient.hx:256: characters 20-34 : Type not found : flash.LoadVars

@SlavaRa

### PR DESCRIPTION
**Pull request by elsassph**
AS2 code used in place of AS3, fixes #151

### CODE REVIEW

**Comment by Gama11** [comment]
Any reason this hasn't been merged yet?

For what it's worth, I just checked this branch out locally and fixes compilation of Flixel's unit tests. 👍

**Comment by elsassph** [comment]
Thanks, I forgot a bit about it but I wanted confirmation that real projects function properly.

**Comment by elsassph** [comment]
Pushed as 2.2.3

**Comment by Gama11** [comment]
Thanks!

**Pull request merged**
